<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />

  <title>BitSkins - Buy &amp; Sell CS:GO, Dota 2 skins</title>
  <meta name="description" content="Discover the best deals on CS2, CSGO, Dota 2 skins at BitSkins, the leading market for trading in-game items. Safe, fast, and secure transactions with instant withdrawals. Join millions of gamers and start trading today!">
  <meta name="keywords" content="BitSkins, in-game items, gaming market, digital skins, secure skin transactions, skin trading, CS2 skins, buy CS2 skins, sell CS2 skins, Dota 2 skins, buy Dota 2 skins, sell Dota 2 skins">
  <meta name="author" content="BitSkins">

  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#121720">
  <meta name="msapplication-config" content="/favicon/browserconfig.xml">
  <meta name="theme-color" content="#121720">
  <link rel="icon" href="/favicon.ico">

  <meta property="og:title" content="BitSkins - Buy &amp; Sell CS:GO, Dota 2 skins">
  <meta property="og:description" content="Discover the best deals on CS2, CSGO, Dota 2 skins at BitSkins, the leading market for trading in-game items. Safe, fast, and secure transactions with instant withdrawals. Join millions of gamers and start trading today!">
  <meta property="og:type" content="website">
  <meta property="og:image" content="https://bitskins.com/img/preview_big.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="627">
  <meta property="og:url" content="https://bitskins.com/api/openapi.yaml">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@BitSkinsCom">
  <meta name="twitter:creator" content="@BitSkinsCom">
  <meta name="twitter:title" content="BitSkins - Buy &amp; Sell CS:GO, Dota 2 skins">
  <meta name="twitter:description" content="Discover the best deals on CS2, CSGO, Dota 2 skins at BitSkins, the leading market for trading in-game items. Safe, fast, and secure transactions with instant withdrawals. Join millions of gamers and start trading today!">
  <meta name="twitter:image" content="https://bitskins.com/img/preview_big.jpg">
  <meta name="twitter:domain" content="bitskins.com">
  <meta name="twitter:url" content="https://bitskins.com/api/openapi.yaml">

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="preconnect" href="https://api.bitskins.com" crossorigin>
  <link rel="preconnect" href="wss://ws.bitskins.com" crossorigin>
  <link rel="preconnect" href="https://ss.bitskins.com" crossorigin>
  <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>
  <link rel="preconnect" href="https://www.google-analytics.com" crossorigin>
  <link rel="preconnect" href="https://connect.facebook.net" crossorigin>
  <link rel="preconnect" href="https://steamcommunity-a.akamaihd.net" crossorigin>
  <link rel="canonical" href="https://bitskins.com/api/openapi.yaml" />
  <link rel="alternate" hreflang="en" href="https://bitskins.com/api/openapi.yaml" />
  <link rel="alternate" hreflang="fr" href="https://bitskins.com/fr/api/openapi.yaml" />
  <link rel="alternate" hreflang="pl" href="https://bitskins.com/pl/api/openapi.yaml" />
  <link rel="alternate" hreflang="ru" href="https://bitskins.com/ru/api/openapi.yaml" />
  <link rel="alternate" hreflang="zh" href="https://bitskins.com/zh/api/openapi.yaml" />
  <link rel="alternate" hreflang="de" href="https://bitskins.com/de/api/openapi.yaml" />
  <link rel="alternate" hreflang="pt" href="https://bitskins.com/pt/api/openapi.yaml" />
  <link rel="alternate" hreflang="id" href="https://bitskins.com/id/api/openapi.yaml" />
  <link rel="alternate" hreflang="hi" href="https://bitskins.com/hi/api/openapi.yaml" />
  <link rel="alternate" hreflang="es" href="https://bitskins.com/es/api/openapi.yaml" />
  <link rel="alternate" hreflang="ja" href="https://bitskins.com/ja/api/openapi.yaml" />
  <link rel="alternate" hreflang="ar" href="https://bitskins.com/ar/api/openapi.yaml" />
  <style>
      html, body { background-color: #121720; color: #fff; margin: 0; height: 100% }
  </style>
  <!--head-->
  
  
</head>
<body>
  <div id="app">
      <style>body { border-top: #191E26 75px solid; position: relative; box-sizing: border-box; } body::before { position: absolute; left: calc(50% - 100px); top: -53px; content: ''; /* content: url(/img/logo.svg); */ } @media (max-width: 767px) { body { border-bottom: #191e26 50px solid; } }</style>
  </div>
  <noscript>
      <div style="font-size: 24px">BitSkins</div>
      <div>You need to enable JavaScript</div>
      <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W5MVH5G" height="0" width="0" style="display:none;visibility:hidden"></iframe>
      <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1095893071426584&ev=PageView&noscript=1" alt="" />
  </noscript>
  <link rel="preload" href="/assets/index-DBo8RGvo.css" as="style" onload="this.onload=null;this.rel='stylesheet'"><script type="module" crossorigin src="/assets/index-BICFrj2t.js"></script>
  <script defer src="/js/script.js"></script>
  <script defer src="/js/fungerprunt.js"></script>
  <script defer src="/js/more.js"></script>
  <link rel="preload" href="/font/index.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
</body>
</html>
